version: '3'
services:
  web:
    image: node:18.19.0-alpine3.18 # Use the Node.js image with a specific version
    container_name: react-app
    working_dir: /app
    volumes:
      - ./:/app # Replace 'your-react-app' with your actual app directory
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for better file watching in containers
    command: sh -c "npm install --legacy-peer-deps && npm start"
